### ISSUE TITLE
License check timeout produces false unhandled error in Core scenarios

### ISSUE THREAD

**Issue by thelontx** [NewPath-Consulting/quickbooks-for-wildapricot#117]
This originally occurred ~ Apr 15, 2024 with BIAC.  It reoccurred on Aug 31, 2024 with BIAC and TAC.   (A separate API limits issue came up at the same time and this issue was never properly documented.)

Analysis from Apr 2024:

Root issue:
The License check timed out, sending the scenarios into a “license failure” mode.

Contributing issue:
My check to see what kind of license failure exists did not work as expected.  The options are invalid key, expired key, unknown error.    This situation should have produced the “unknown error” option.  Instead, it produced the “expired key” result.   I honestly can’t figure out why. I’m not sure if you see anything I missed.

More info:   (supporting screenshots attached)
a) My license check scenario looks for the “expiration date” returned from the license check call.   If the check fails, the scenario goes into error handling.  In this case, the timeout message was returned, so it went to error handling.
b) The field “expiration date” does not exist inside the “timeout message” from the license check, yet the Make scenario still treats the timeout message as a valid date for some reason.   Thus, the “License Error Type” was set to “Expired License”.
c) The email that goes to the admin includes some switch statements based on the “License Error Type”.   If License Error Type = “Expired License”, the HTML includes the expiration date in the text of the email.   That expiration date field does not exists and caused the format date function inside the Email module to fail.

Recommended resolution:
Add additional error handling following the license check.  Use the following logic and actions as part of the error handling.
- If a value for 'data.expiration date' is not returned from the HTTP call, assume there is a timeout.
- If a timeout is detected, allow the scenario to run normally. i.e. assume that the scenario is not expired.
- If a timeout is detected, send an additional email to NPC support with an FYI about the occurrence.   i.e. scenario was allowed to run normally without a valid license check.

Scope of changes:  (repeat for all Core scenarios - Donation, Invoice, Payment)
- filter following router 333 (just after http license check) - add an OR option for 'data.expiration date' does not exist
- new route following router 203 - route should have filter for 'data.expiration date' does not exist.   Following the filter, an email module will be installed that sends an FYI message to NPC support staff.   Message is an FYI that timeout occurred and scenario was allowed to run normally.
- invalid key/date route for router 203 - should have a filter to block progress if 'data.expiration date' does not exist.

**Comment by thelontx** [comment]
Updated info....   
Further investigation shows that the received error message from the HTTP call is from the NewPath website's firewall.  For some reason the request was being blocked.

Alex found this reference that suggested that was the cause:
https://my.hawkhost.com/knowledgebase/20/Please-wait-while-your-request-is-being-verified...-message-sho....html#:~:text=If%20an%20IP%20address%20is%20detected%20as%20potentially%20malicious%20or

The person managing the site has added Make.com's IP addresses to the whitelist.
https://www.make.com/en/help/connections/allowing-connections-to-and-from-make-ip-addresses

For now, this is the only action being taken with the assumption that it will resolve the issue.

Another option that may be chosen in the future, replace the NPC redirect URL with the direct webhook URL.   Athe time of this post, that URL is:
https://hook.us1.make.com/8euj9o9frkj3wz2nqm6xmcp4y1mdy5tp

**Comment by asirota** [comment]
Let's close this for now as the firewall should be ok unless Make's IP address ranges change.
